import type {NextPage} from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

const links = ['interceptors', 'cancellation'];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {links.map(v => (
          <Link key={v} href={`/${v}`}>
            <a>{v}</a>
          </Link>
        ))}
      </main>
    </div>
  );
};

export default Home;
